### ISSUE TITLE
Consecutive splits don't work

### ISSUE THREAD

**Issue by andrea96** [acrisci/i3ipc-python#117]
I don't even know if this is a bug, I'm using sway (1.0) and I didn't try with i3, probably it's a problem of sway. However I would like to open 3 terminals (for example termite) in a not linear way e.g. I open the first and the second, then I change the split orientation and then I open the last terminal.

```python
#!/usr/bin/env python

import i3ipc
from time import sleep

sway = i3ipc.Connection()

sway.command("""
workspace 10
split h
exec termite
exec termite
split v
exec termite
""")
```

This doesn't work and simply opens all the three terminals but with the same splitting options (the last split command). 
What led me to this is that I was trying to write a script to run some applications at startup in a specific workspace and with a specific "layout".

If I reach my goal I would like to create a simple script which take an xml (or json) file with the names of the applications and the positions and automatically opens them in the right workspace with the correct layouts. I didn't find something like this in the examples folder of this repository.

**Comment by acrisci** [comment]
This isn't a bug in the library, but I'll support you in this issue because this is an interesting idea.

I think you are assuming that the `exec termite` command is synchronous. What this is actually doing is starting the termite process and then going to the next command. It does not wait for the termite window to appear.

What you have to do is use the exec command and then wait for the window. Something like this:

```python3
i3.command('exec termite')

def on_window_open(i3, e):
    # TODO match e.container to the process that was started with the exec command
    if e.container.title == 'termite':
        # TODO do whatever with the window you just opened

i3.on('window::open', on_window_open)
```
